### ISSUE TITLE
Codebuild Credentials & IAM

### ISSUE THREAD

**Issue by kurtmaile** [jdhollis/lambda-deployment-example#1]
Hi,

Thanks for this.  Just curious if the jq work to get the right keys is still the way a year on?  Or can codebuild now assume a role via trust instead?  Assume the jq was a workaround back then as this wasnt supported.

Great read BTW thanks - Im looking at a similar setup, anything drastically change in the last year that you would change your setup?

Cheers!

**Comment by jdhollis** [comment]
Actually, yes. This is outdated code. I'm working on an updated version.

The issue wasn't with CodeBuild, but rather with Terraform at the time. It wasn't able to automatically use container credentials. It looks like this was fixed sometime around v0.11.7: https://github.com/hashicorp/terraform/issues/8746

**Comment by kurtmaile** [comment]
Great can’t wait to see the updated version then cheers
